### ISSUE TITLE
Размножение диалоговых окон Bluetooth

### ISSUE THREAD

**Issue by a-n-d-r** [flipperdevices/Flipper-Android-App#132]
**Если нажать кнопку "отклонить" или "назад" в диалоговом окне включения Bluetooth, окно пропадает и появляется 2 окна. Потом 3, 4, 5 и т.д. по нарастающей. Выйти из приложения по двойному клику кнопки "назад" в таком случае не удаётся.**

**Шаги по воспроизведению:**
1. Зайти в приложение
2. Нажать на обе синие кнопки (принять соглашение и анбординг)
3. Нажать "отклонить" или "назад" в диалоговом окне включения Bluetooth

**Ожидаемое поведение:**
При нажатии кнопки "отклонить" пользователя возвращают на анбординг с пояснительной запиской по типу "без Bluetooth приложение работать не будет", либо всплывает уведомление с таким же содержанием, но уже без возвращения на анбординг.

**Прикрепляю [запись экрана](https://youtu.be/sIwgyjf16nk)  с демонстрацией бага**

**Comment by LionZXY** [comment]
Большое спасибо за баг! Исправлено в последней версии, проверь :)
Оформление огонь!
