### ISSUE TITLE
Sync crashes

### ISSUE THREAD

**Issue by qqmajikpp** [flipperdevices/Flipper-Android-App#209]
**Describe the bug**

Samsung S20+
Android 12

Syncing worked the first time on my device. Now syncing just causes the app the crash. Tried clearing data and cache. Remove and reinstall does not change issue. File manager and streaming work fine.

**To Reproduce**
1. Switch on...
2. Press button '....'
3. Wait for the moon phase
4. It burns

**Expected behavior**

**Logs**
Add debug logs

**Target**
Specify the target

**Additional context**

**Comment by LionZXY** [comment]
What version do you have?

**Comment by MVGavrilov** [comment]
Same problem with samsung a8, the app crashes in few (3-4) sec after connection to the flipper. FW version: 4b4576b, same problem was with one of the previous versions (8... dont remember). App version: 1.1.1

**Comment by LionZXY** [comment]
Try latest beta version, please

**Comment by MVGavrilov** [comment]
1.1.2.320 (pre release) same problem

**Comment by LionZXY** [comment]
Use the latest release in the official Flipper Zero firmware please.  
Repeatable?

**Comment by MVGavrilov** [comment]
Same with release 0.58.1

**Comment by LionZXY** [comment]
Please, remove `Link (Link�s Awakening).nfc` file
