### ISSUE TITLE
Samsung "my files" file manager bug

### ISSUE THREAD

**Issue by SHMAUS-Carter** [flipperdevices/Flipper-Android-App#218]
Using the Samsung's my files I am unable to upload any file to flipper

**Expected behavior**
 Flipper shows up in open with list.
For supported files types

**Target**
1.0

**Additional context**
Works correctly with any third party file manager such as FX or a deep link file manager that calls the native android "files" file manager.

components/deeplink/impl/src/main/AndroidManifest.xml

**Comment by LionZXY** [comment]
Is there somewhere I can download this file manager?

**Comment by GottZ** [comment]
same issue with https://play.google.com/store/apps/details?id=pl.solidexplorer2

**Comment by GottZ** [comment]
fx doesn't work for me either.
file is a .txt

**Comment by Programistich** [comment]
Hi, I can try reproduce your issue and try fix this
Thx for report!

**Comment by LionZXY** [comment]
Fixed in https://github.com/flipperdevices/Flipper-Android-App/commit/2ee18a3fcc7e25bfb7d4478062002150576233ec for import from file manager
