### ISSUE TITLE
Archive tab

### ISSUE THREAD

**Issue by juicyhacker** [flipperdevices/Flipper-Android-App#321]
**Problem:**

Can't see my files in the archive tab because I put them in subfolders.

Can't play files from archive tab, only open. so I still need the flipper to play a file.

**Solution:**

Index subfolders, so that we can navigatie through subfolders using the app.

Make it able to play files using the app, not just opening. 
example: playing a subfile using the app so you don't have to touch the flipper.

**Comment by LionZXY** [comment]
> Make it able to play files using the app, not just opening.

Already in latest dev. We'll have a release soon!

> Can't see my files in the archive tab because I put them in subfolders.

Duplicate https://github.com/flipperdevices/Flipper-Android-App/issues/284
