### ISSUE TITLE
Wrong date clock 

### ISSUE THREAD

**Issue by Foul** [flipperdevices/Flipper-Android-App#324]
### Describe the bug.

When linked/synced to the PC APP, date clock is ok.
When linked/synced to the Android APP, date clock is wrong.
![IMG_20220808_012420](https://user-images.githubusercontent.com/829842/183315245-440915d8-18e3-4c49-8b38-8bdfcfb136de.jpg)

### Reproduction

Switch on your flipper zero
Sync the Android APP via Bluetooth
Check your date/year under Clock App !
(day/month are good)

### Target

Android App.

**Comment by LionZXY** [comment]
Please, check again with latest beta

**Comment by Foul** [comment]
same thing with beta from today :(

**Comment by LionZXY** [comment]
Oops) Thank you!

**Comment by Foul** [comment]
Seems to work normally with latest fw and app. You can let close.
