### ISSUE TITLE
Syncing wipes/edits favorites.txt

### ISSUE THREAD

**Issue by thisiskyle** [flipperdevices/Flipper-Android-App#331]
**Describe the bug**

 If files on the flipper are sorted into subfolders beyond the root application folder (example: ```/ext/subghz/sub_folder/file.sub```) and are also in favorites.txt, are removed from favorites.txt after syncing with the android app.

Files that are not in subfolders (example: ```/ext/subghz/file.sub```) act as expected and remain in favorites.txt

Possibly related to issue #284

**To Reproduce**

1. Place a file on the flipper in a subfolder such as ```/ext/nfc/my_folder/file.nfc```
2. On flipper, pin the file to your favorites
3. Connect flipper to android app via bluetooth
4. Sync device and app
5. Check favorites.txt

**Expected behavior**
Pinned/Favorite files should remain in favorites.txt after syncing with android app

**Comment by LionZXY** [comment]
Should be fixed in the current dev. Please check!
