### ISSUE TITLE
Android app no longer detects Flipper

### ISSUE THREAD

**Issue by RogueMaster** [flipperdevices/Flipper-Android-App#335]
**Describe the bug**
Android app no longer detects Flipper on CFW with a name change for device so it doesn't transmit "Flipper" in the name.

**To Reproduce**
1. Install Custom FW with line changes compiled in furi_hal_version.c so instead of Flipper it says anything else.
2. Try to connect with Android app via bluetooth

**Expected behavior**
It connecting, like IOS app can. Possibly identifying other flippers with mac?

**Comment by skotopes** [comment]
There are reasons why we use "Flipper" in the BLE device name, including ability to find flipper before establishing connection. 

You are on your own with this issue.
