### ISSUE TITLE
Mifare tag UID not editable

### ISSUE THREAD

**Issue by KusakabeShi** [flipperdevices/Flipper-Android-App#344]
# What are you want to add or change
I want edit these parts
# What questions do you have
These parts are not editable
![image](https://user-images.githubusercontent.com/73118488/187225247-d2e791a4-d080-416b-a9e2-b19506b1c6fd.png)

**Comment by LionZXY** [comment]
We don't allow to change UID in MFC 0 block right now scince you have to modify UID section in Flipper File Format too. May be we add this later

**Comment by LionZXY** [comment]
Fixed by 2114c52ffc86b24ce15f7bac364041304d27eb30
