### ISSUE TITLE
Can't connect to Flipper

### ISSUE THREAD

**Issue by josqu4red** [flipperdevices/Flipper-Android-App#347]
* Platform: Samsung GS9 with Android 10, app version 1.2.0.
* Flipper version 0.65.2 (latest release, tested with 0.64.3)

Symptoms:
After pairing with the device, an android popup shows `can't find version gatt service` and then application states that firmware is outdated and not supported.
Tried setting "Ignored unsupported firmware version" but it only seems worse.
Internets do not seem to know much about that "gatt service", don't really know where to look :(

Thanks for your help :)

**Comment by LionZXY** [comment]
Do you have a chance to test it on another phone?

**Comment by josqu4red** [comment]
I only own one Android device unfortunately...

**Comment by LionZXY** [comment]
It looks like a bug with your phone :(

Do you have other BLE devices working?
