### ISSUE TITLE
Install firmware from Flipper

### ISSUE THREAD

**Issue by denysvitali** [flipperdevices/Flipper-Android-App#377]
**Is your feature request related to a problem? Please describe.**
It seems like the Android app can't handle custom firmware files. This effectively means that one can't flash a custom firmware for the Flipper Zero using their Android device.

**Describe the solution you'd like**
User is able to download a firmware from the internet (outside the app), click on "Open with..." / "Share" and select tbe Flipper app.

The Flipper all should then prompt the installation of the firmware.

**Describe alternatives you've considered**
N/A

**Additional context**

**Procedure 1**

Steps to reproduce:

1. Open a File Manager (in this case, Material Files from F-Droid)
2. Navigate to the directiry that contains the ".tgz"/ ".zip" of the firmware.
3. Select the firmware file three dots on the right
4. Click "Open With"
5. Note that the Flipper app doesn't show there
6. Select "Open As"
7. Select the "Other" option
8. Select the "Flipper" app

Result:
The app opens for a split second, then closes jtself automatically.

**Procedure 2**

Steps to reproduce:

1. Open the file manager
2. Navigate to the directory contained the _extracted firmware_ (.tgz, .zip)
3. Click on the update manifest `update.fuf`
4. Select the Flipper app

Result:

The following screen appears, but nothing can be done:
![Screenshot_2022-09-18-10-09-51-61_7588ec92b699bdd924e4cc049cbf9f1b](https://user-images.githubusercontent.com/4939519/190892443-a3557387-ad7d-44e3-876e-c36f29f2fc81.jpg)

**Comment by Programistich** [comment]
Hello!  Thanks for the comments.  And it's true, right now there is no way to load custom firmware from a file, but in the future it may appear.
