### ISSUE TITLE
Request: support android 13 Themed app icons 

### ISSUE THREAD

**Issue by mralext20** [flipperdevices/Flipper-Android-App#386]
feature: https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by Programistich** [comment]
This?
![Screenshot_20220921-150132.png](https://user-images.githubusercontent.com/35292229/191498663-11f0698f-2d09-459f-be9c-4f2505b002c9.png)

**Comment by Programistich** [comment]
Or I create best variants
![Screenshot_20220921-151416.png](https://user-images.githubusercontent.com/35292229/191501146-cdb0592f-3f54-4224-a632-7f0d6307bdd4.png)

**Comment by Programistich** [comment]
![Screenshot_20220921-151416.png](https://user-images.githubusercontent.com/35292229/191501208-78bbce56-f50f-47ac-8712-d7cc160d74f2.png)
