### ISSUE TITLE
Hide or minimize update button when up to date firmware

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/Flipper-Android-App#393]
# What are you want to add or change

Update button should not be so important when flipper is up to date.

# What questions do you have

Users should be allowed to re-update or update from a custom firmware/unknown version
Users should have a custom firmware install button

**Comment by LionZXY** [comment]
This will cause jumps in the interface and result in an inconsistent design

**Comment by kowalski7cc** [comment]
Maybe something like change button color and text:
![image](https://user-images.githubusercontent.com/5065094/192260900-79622edb-948d-4cf2-a2b8-85e971c79983.png)

**Comment by kowalski7cc** [comment]
Edit: so I updated anyway even if my Flipper was up to date. Flipper crashed and mobapp showed correctly "no updates"

**Comment by LionZXY** [comment]
This was updated region, most likely.
