### ISSUE TITLE
Copy to clip board for synced data 

### ISSUE THREAD

**Issue by arunderwood** [flipperdevices/Flipper-Android-App#405]
In the Archive I can view some of the captures I've synced to my phone but I cannot copy the data to my Android clipboard.  If the data/keys fields in the Archive objects were selectable/copyable it would make it easier to put them into a hex/decimal converter or otherwise work with the data.

**Comment by LionZXY** [comment]
Can you provide an example of the data and key where you would like to copy?

**Comment by LionZXY** [comment]
Please, provide additional infromation
