### ISSUE TITLE
Dark theme incorrect colors

### ISSUE THREAD

**Issue by slartus** [flipperdevices/Flipper-Android-App#433]
In Dark Theme active tab text color is hard to see

**Describe the bug**
device: Xiaomi mi8, miui 12.0.3, android: 10
System theme: Dark
flipper theme: System

**Additional content**
![image](https://user-images.githubusercontent.com/1107015/200504152-8ff2f2c3-7869-43b7-aa59-b693c2d490fd.png)

**Comment by LionZXY** [comment]
O_o
Okay, your phone is strange, thank you for bug report. We are going to fix it in future

**Comment by slartus** [comment]
just add
` <item name="android:forceDarkAllowed" tools:targetApi="q">false</item>`
result:
![image](https://user-images.githubusercontent.com/1107015/200510274-097f69a2-20df-44aa-94f4-fefcae9b3eb1.png)

**Comment by LionZXY** [comment]
Fixed
