### ISSUE TITLE
Allow Sending INFRARED signals

### ISSUE THREAD

**Issue by TQMatvey** [flipperdevices/Flipper-Android-App#447]
**Is your feature request related to a problem? Please describe.**
why is it possible to send subghz signal, emulate NFC, RFID, iButton, but not infrared?

**Describe the solution you'd like**
Allow sending Infrared signals from App -> Archive -> Infrared signal in same way as i would send a subghz signal, or any other supported signal

Also it is possible to send IR signals with ios app but not android....

**Describe alternatives you've considered**

**Additional context**
I asked this in Telegram group multiple times, but got a response of "maybeee, soon, why is it needed?"

**Comment by evaneaston** [comment]
I agree this would be nice.

**Comment by LionZXY** [comment]
We will add this, in the future, it is already planned

**Comment by TQMatvey** [comment]
still waiting :D

**Comment by akoskoronka** [comment]
The first thing I noticed when I tried the app remote control was the lack of this feature.
It would be very nice, could use the flipper as an ir blaster.

**Comment by TQMatvey** [comment]
> We will add this, in the future, it is already planned

well, it's been almost a year from me opening the issue, still no feature present..

**Comment by LionZXY** [comment]
This was done a long time ago, forgot to close it
