### ISSUE TITLE
Android SubGhz widget tx loop instead of one shot tx

### ISSUE THREAD

**Issue by michelinok** [flipperdevices/Flipper-Android-App#460]
The problem is that if i send a subghz via widget it keeps sending instead of a "one shot" transmission

**To Reproduce**
Put a subghz widget on the phone desktop and try to send it.

**Expected behavior**
One shot transmission

**Target**
Android

**Comment by LionZXY** [comment]
This is expected behavior - you can't make a hold on a widget. We can create a separate type of widget for single-click.

**Comment by michelinok** [comment]
> This is expected behavior - you can't make a hold on a widget. We can create a separate type of widget for single-click.

That will act like a normal single "push" on a button on a remote, that would be great!

**Comment by michelinok** [comment]
Anyway....I think that a single-click single tx is what it must do...i don't see why it should tx continously...if you can, please, explain me why this behavior!
Many thanks!
Mike

**Comment by LionZXY** [comment]
What if you have a garage door or curtains that open on the hold of a button?

**Comment by michelinok** [comment]
> What if you have a garage door or curtains that open on the hold of a button?

Really...never happened to me.

One solution can be to have two types of widget or a configurable widget (loop on/off).

**Comment by evaneaston** [comment]
I agree that it would be nice to have a second widget type which is a one shot.
