### ISSUE TITLE
Remote Send Continuous - Not working

### ISSUE THREAD

**Issue by DakotaMcCutch** [flipperdevices/Flipper-Android-App#475]
**Describe the bug**
When pressing the send button on a saved capture, it says hold to send continuously. But once the signals are done, even when holding the button, it just changes the button to send and doesn't continuously send

**To Reproduce**
1. Open the App
2. Click a SubGhz capture
3. Click and hold send
4. Sends once, not continuously

**Expected behavior**
Sends continuously

**Comment by skotopes** [comment]
Can you provide used software versions, device info(can be gathered throw cli `device_info`) and file that you trying to send

**Comment by LionZXY** [comment]
Open back up, please, when you provide the information
