### ISSUE TITLE
https://github.com/flipperdevices/Flipper-Android-App/issues/478#issue-1510709374

### ISSUE THREAD

**Issue by Gwill55** [flipperdevices/Flipper-Android-App#499]
**Describe the bug**

**To Reproduce**
1. Switch on...
2. Press button '....'
3. Wait for the moon phase
4. It burns

**Expected behavior**

**Logs**
Add debug logs

**Target**
Specify the target

**Additional context**

**Comment by LionZXY** [comment]
Duplicate of https://github.com/flipperdevices/Flipper-Android-App/issues/478#issue-1510709374
