### ISSUE TITLE
Update AGP to last released version

### ISSUE THREAD

**Issue by LionZXY** [flipperdevices/Flipper-Android-App#53]
# Describe you problem here

Hi. In this Pull Request, I tried to update the Android Gradle Plugin in the project ([here](https://github.com/flipperdevices/Flipper-Android-App/pull/52/)), but it just didn't work that way. I would be happy if someone could update the Gradle Plugin. That way we can keep the project up to date.

**Comment by rougsig** [comment]
I think we can close that issue @LionZXY

**Comment by LionZXY** [comment]
Thank you, @rougsig
