### ISSUE TITLE
mfkeys app incorrectly displays and saves keys that contain leading zeros

### ISSUE THREAD

**Issue by fersingb** [flipperdevices/Flipper-Android-App#532]
**Describe the bug**
Keys that start with a `0` are not displayed/saved properly. The leading zero is missing, resulting in an invalid key

**To Reproduce**
1. create a file `.mfkey32.log` with the following content: `Sec 0 key A cuid 2f05ec42 nt0 bebf5b50 nr0 d34d3251 ar0 a4463233 nt1 a3cfc299 nr1 507d9fde ar1 dac188a7`
2. Save if in /ext/nfc/
3. Run the Android mfkey app in NFC Tools
4. Notice that the leading 0 is missing

**Expected behavior**
Leading 0 is correctly displayed and saved

Recovering the key using the CLI tool works without any issue:
```
./mfkey32v2 2f05ec42 bebf5b50 d34d3251 a4463233 a3cfc299 507d9fde dac188a7
MIFARE Classic key recovery - based 32 bits of keystream  VERSION2
Recover key from two 32-bit reader authentication answers only
This version implements Moebius two different nonce solution (like the supercard)

Recovering key for:
    uid: 2f05ec42
   nt_0: bebf5b50
 {nr_0}: d34d3251
 {ar_0}: a4463233
   nt_1: a3cfc299
 {nr_1}: 507d9fde
 {ar_1}: dac188a7

LFSR successors of the tag challenge:
  nt': 403f82e6
 nt'': c6b4c9a2

Keystream used to generate {ar} and {at}:
  ks2: e479b0d5

Found Key: [0a1b2c3d4e5f]
```

**Comment by fersingb** [comment]
@LionZXY you actually reproduced it. The key is missing the first `0` The key should be `0a1b2c3d4e5f`

**Comment by LionZXY** [comment]
Oh, thank you, it's my fault
