### ISSUE TITLE
Remove Countly tracker library.

### ISSUE THREAD

**Issue by EvanCarroll** [flipperdevices/Flipper-Android-App#593]
Because of the nature of the Flipper Zero, it seems like it should show no tracker libraries. Currently TrackerControl Android identifies [Countly](https://countly.com/) in the android app. It would be nice if there was a build switch to build without this, at least for F-Droid.

The metric gathering is done in [`MetricApiImpl`](
https://github.com/flipperdevices/Flipper-Android-App/blob/4edd4c6791d2694289133e1bc332880d30183f3d/components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/api/MetricApiImpl.kt#L10)

It seems like it's posting to this site, https://countly.lionzxy.ru/ which doesn't seem to exist. I'm guessing this resolves locally for development and gets set in [Gradle when building](https://github.com/flipperdevices/Flipper-Android-App/blob/4edd4c6791d2694289133e1bc332880d30183f3d/.github/workflows/release.yml#LL62C1-L63C1)

This telemetry is used in the calls to `reportSimpleEvent` and `reportComplexEvent`, which are used in things like the [MiFare screen](https://github.com/flipperdevices/Flipper-Android-App/blob/4edd4c6791d2694289133e1bc332880d30183f3d/components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/viewmodel/MfKey32ViewModel.kt#LL128C19-L128C36). It sounds unwise and incriminating to have a third party with all the metadata (ip, timestamp) of when they were using RFID functionality of the Flipper.

-----

Aside from the normal privacy concerns, [Countly goes on to say in their privacy policy](https://countly.com/legal/privacy-policy),

>  We will refuse government and law enforcement requests for data if we believe a request is too broad or unrelated to its stated purpose. However, **we may cooperate if we believe the requested information is necessary and appropriate to comply with legal process, to protect our own rights and property, to protect the safety of the public and any person, to prevent a crime, or to prevent what we reasonably believe to be illegal, legally actionable, or unethical activity.**

So they could presumably "cooperate" with any "request" (not even a subpoena) from the "government and law enforcement" (not specific to the ones that have legal jurisdiction over them) handing over data if they **believe** the activity is merely "unethical". And without notification. That's a pretty low bar.

**Comment by LionZXY** [comment]
First of all, it is worth mentioning that all collected information is completely **anonymous** and does **not contain user data**. From the collected information it is **impossible** to recover the user's data or his identity. 
Secondly, it is worth noting that the next build of FDroid will no longer contain metrics, this is the responsibility of the environment variable "ORG_GRADLE_PROJECT_is_metric_enabled". 

You can verify the purity of the metrics, since all of our code is open-source and the builds are reproducible

**Comment by EvanCarroll** [comment]
@LionZXY F-Droid is still showing telemetry is enabled on the build,

https://f-droid.org/packages/com.flipperdevices.app/

> Anti-Features
This app has features you may not like. [Learn more!](https://f-droid.org/en/docs/Anti-Features/) [This app tracks and reports your activity](https://f-droid.org/en/docs/Anti-Features/#Tracking)

**Comment by EvanCarroll** [comment]
@Wjxfi don't be a dick, @LionZXY has quite obviously tried to remove the tracker libraries for just us F-Droid users. It seems like he is trying though not successful. I also want the trackers removed. F-Droid is doing the right thing by saying that there are trackers. And @LionZXY seems to be doing the right thing by acknowledging this is something at least some of his users are very passionate about and trying to scrub them.

The real take away here is that F-Droid is adding tremendous value by at least pointing out that there is potentially incriminating telemetry on the app. Moreover, for the time being you can use TrackerControl to block the telemetry.
