### ISSUE TITLE
Unleashed not working when I try and download it .

### ISSUE THREAD

**Issue by Sbk34** [flipperdevices/Flipper-Android-App#631]
I have tried upgrading my flippers capabilities by flashing unleashed by xmaster x  the problem I keep running into is I can't get it to work on flipper . I've followed all the instructions and still nothing . I'm trying on a laptop and a Mac os . Nothing . I do t understand why and it's becoming really frustrating.

**Comment by LionZXY** [comment]
Please leave bugs of third-party firmware in third-party firmware repositories
