### ISSUE TITLE
Apps displaying as uninstalled even after installation.

### ISSUE THREAD

**Issue by lolroger** [flipperdevices/Flipper-Android-App#654]
**Describe the bug**
I have noticed that after installing several apps on the app hub, they do not persistently display as "Installed" and will still have the install button available for selection on the hub. The apps are indeed installed though and available for use in the Flipper's application menu.

**To Reproduce**
1. Open Flipper Zero app
2. Navigate to Hub
3. Open Apps
4. Navigate to one of the recent apps appearing at the bottom of the page under "All Apps"
5. Install one or more apps by clicking the orange install button.
6. Wait until installation is complete.
7. Close or restart the Flipper Zero app.
8. Navigate back to App page.
9. Those same apps that were installed in step 4 will not appear as "installed" and the orange install button is still available for selection.
10. Open the application menu on the Flipper Zero.
11. Those same apps should be available on the Flipper Zero for use, even though the option to install them is still present on the hub's app page.

**Expected behavior**
Apps that are installed on the Flipper Zero should be displayed as such on the hub's app page and should not have the orange install button still available for selection.

**Comment by LionZXY** [comment]
The catalog shows applications installed only from the catalog. This is expected behaviour, as we can neither check for an update for such an application, nor understand what version it is installed in
