### ISSUE TITLE
Install Application button flashes then does nothing

### ISSUE THREAD

**Issue by Zakenbacon** [flipperdevices/Flipper-Android-App#662]
Android user here. Every time I try to install an app from the store, it quickly shows the 0% screen and then reverts back to the INSTALL button. Are there currently any workarounds?

**Comment by theHausdorffMetric** [comment]
Hi, 
same problem here on Release 0.87.0 with android app 1.6.1 (unkown) from F-Droid.
I "solved" it by uninstalling app (from F-Droid) and reinstalling 1.6.1110 (Google Play/Release).
Could it be that the F-Droid version ist older?

**Comment by LionZXY** [comment]
Please, attach log/report

**Comment by LionZXY** [comment]
Duplicate #658
