### ISSUE TITLE
Mobile app crashes

### ISSUE THREAD

**Issue by mouffrac** [flipperdevices/Flipper-Android-App#664]
**Describe the bug**
When I try to connect the Flipper Zero to my Mobile phone with bluetooth, the app crashes

**To Reproduce**
1. Launch the Flipper Mobile App
2. Wait for the Mobile app to connect to Flipper Zero
3. The Firmware version appears (0.87.0)
4. The app crashes 

**Expected behavior**
The Flipper zero should be connected to my phone

**Logs**
Add debug logs

**Target**
Specify the target

**Additional context**

**Comment by LionZXY** [comment]
Try reboot phone

**Comment by LionZXY** [comment]
Duplicate #477
