### ISSUE TITLE
Phantom Bluetooth

### ISSUE THREAD

**Issue by SuperVDF** [flipperdevices/Flipper-Android-App#667]
/### Describe the bug.

Flipper showing active Bluetooth connection when Bluetooth is not on, on mobile device. Using Android 13 latest update. Screen grab provided below.

### Reproduction

Don't use the flipper for 1-3 days, Bluetooth shows connected.

![Screenshot_20230629-090918_Settings](https://github.com/flipperdevices/flipperzero-firmware/assets/133692486/e158afd8-a9c0-4a47-aa84-111119682839)

**Comment by skotopes** [comment]
@LionZXY looks like this belongs here

**Comment by LionZXY** [comment]
Looks like expected behavior - please provide more information and steps to reproduce

**Comment by SuperVDF** [comment]
Hey there, so this issue is most certainly closed now. The phantom Bluetooth connection issue appears to have gone away with the last firmware update. To clarify, the flipper zero would display an active Bluetooth connection (--©) even when Bluetooth on the device (my phone in this case) would be off. This would happen after 2 to 3 days of inactivity with the F0 device. Thank you to the Dev team for looking at this.
