### ISSUE TITLE
App store for Android App from F-droid doesn't work

### ISSUE THREAD

**Issue by ankek** [flipperdevices/Flipper-Android-App#673]
**Describe the bug**
App store for Android App from F-droid doesn't work. When I click on Install button nothing happened. Download bar shown for a second and when become Install button again. I cannot install ANY application from F-droid Android App. But from Android App from Google Play Works fine. All app can be installed.

**To Reproduce**
1. Install  Android App from F-droid
2. Go to Hubs-Apps. Pick any app from list and Press button 'Install' 
3. Download bar shown for a second and imediately stops. Install button shown again.
4. Next install tryouts does not have any effect. Same behavior 
5. It hurts 

**Expected behavior**
Android App from Google Play have no such problem. All apps from list can be installed. When Press button 'Install', app download started and installation process works fine 

**Logs**
Let me know how I can get logs

**Target**
Fix Apps download issues

**Comment by LionZXY** [comment]
Duplicate #658
