### ISSUE TITLE
How to unlock the Flipper zero when you can't remember the code

### ISSUE THREAD

**Issue by Greenas69** [flipperdevices/Flipper-Android-App#728]
# Describe your problem here

**Comment by skotopes** [comment]
Do the reset to initial state:
- Press and hold Up and Back for 30 seconds
- Device will ask you for confirmation, press and hold Right

Also http://docs.flipper.net

**Comment by Greenas69** [comment]
Thank you appreciate that finally worked out what to do. Sorry mate I'm pretty new at this 🥴
