### ISSUE TITLE
App not opening 

### ISSUE THREAD

**Issue by madarauichea** [flipperdevices/Flipper-Android-App#730]
Mow the app is working fine

**Comment by Programistich** [comment]
What is the version of app in your installation?

**Comment by madarauichea** [comment]
1.6.5

**Comment by Programistich** [comment]
Try use 1.6.6, some improvements added

**Comment by madarauichea** [comment]
There is no option to download that version

**Comment by LionZXY** [comment]
Where are you downloading the app from?

**Comment by VectorKappa** [comment]
F-droid, probably. They're very delayed with builds lately.

**Comment by taivlam** [comment]
@madarauichea Could this be closed now?

The app version `1.6.6` is now available on [F-Droid](https://f-droid.org/en/packages/com.flipperdevices.app/), and no longer crashes.
