### ISSUE TITLE
Intents for Tasker

### ISSUE THREAD

**Issue by sollermun** [flipperdevices/Flipper-Android-App#796]
# Describe your problem here
I would like to integrate the Flipper Android App to tasker. Specifically, I want to create a task that will play subghz raw recording.

Is that possible with the Flipper App using intents? Is there a list of intents that I can look to?

I have tried using GadgetBridge, but the problem with that is that it will not play the entire subghz raw file. The F0 stops after 0.5 to 1 second of transmission.

**Comment by LionZXY** [comment]
There is now an API on intents for emulation that is used in Widgets. 
You can see more details here: [WidgetBroadcastReceiver](https://github.com/flipperdevices/Flipper-Android-App/blob/dev/components/widget/impl/src/main/java/com/flipperdevices/widget/impl/broadcast/WidgetBroadcastReceiver.k)
