### ISSUE TITLE
Tip me please

### ISSUE THREAD

**Issue by rougsig** [flipperdevices/Flipper-Android-App#832]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by algora-pbc** [comment]
💎 **rougsig** is offering a **$10** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #832` in the PR body and joining algora.io
