### ISSUE TITLE
Show changelog before update

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/Flipper-Android-App#850]
**Is your feature request related to a problem? Please describe.**
For now, on qFlipper app it's possible to show FW changelog before update. In Android Flipper App is changelog shown only after press update button.

**Describe the solution you'd like**
Add a button + frame/subpage for show changelog without pressing update button. 

**Describe alternatives you've considered**
Connecting FZ to PC and opening qFlipper app for read changelog it's not the best way :) 

**Additional context**
Many thanks!

**Comment by Panda1283** [comment]
hi

**Comment by Tomi2965** [comment]
@LionZXY many thanks! :)
