### ISSUE TITLE
Bluetooth connection to Samsung S24 Ultra doesn't work

### ISSUE THREAD

**Issue by kochpet** [flipperdevices/Flipper-Android-App#867]
Bluetooth connection to Samsung S24 Ultra 
doesn't work

**To Reproduce**
1. Switch on Bluetooth
2. Press button Connect in Adroid App

**Expected behavior**

**Logs**
Add debug logs

**Target**
Specify the target

**Additional context**
![Screenshot_20240525_203438_Flipper](https://github.com/flipperdevices/Flipper-Android-App/assets/95183761/1b1ba1f9-3a69-4252-89af-a7ada0194c0e)

**Comment by LionZXY** [comment]
What if you try to connect from your phone settings? And then in the app.
Can you also attach the logs?
https://docs.flipper.net/mobile-app/bug-report

**Comment by kochpet** [comment]
The phone settings connection doesn't work either, there is a PIN request but no connection is established. I have attached the debug log file, the first connection attempt in the log is with the app, the second directly via the phone Bluetooth.
[terminal_content_1716922186759.txt](https://github.com/flipperdevices/Flipper-Android-App/files/15474697/terminal_content_1716922186759.txt)

**Comment by LionZXY** [comment]
I need logs from the mobile app side. Please send here the ID Bug Report
https://docs.flipper.net/mobile-app/bug-report#wS2g4

**Comment by jdrch** [comment]
WFM on my unlocked S24U.

**Comment by LionZXY** [comment]
Please, anyone with the same problem check if it reproduces for you under the following conditions:
- Install the official firmware
- Delete all pairs from the phone and from the flipper
And try again
