### ISSUE TITLE
Add setting to hide Update button from the main screen

### ISSUE THREAD

**Issue by xcpn** [flipperdevices/Flipper-Android-App#936]
**Is your feature request related to a problem? Please describe.**

A lot of Flipper Zero users like to tinker with the device and a lot of them end up installing a different firmware all together. Since Flipper Zero allows for easy firmware installations to begin with, it would be good idea to have a setting for the Update button on the main screen to be hidden if desired so we can prevent accidentally erasing the custom firmware.

**Describe the solution you'd like**

Add a setting inside the Options section to toggle a hide/unhide state of the Update button.

**Describe alternatives you've considered**

None

**Additional context**

I have not tried tapping on the Update button to see if there is a warning before it starts updating, because I don't want lose the custom firmware.

**Comment by LionZXY** [comment]
It takes a very long time to update. I don't think it is possible to ‘accidentally’ update the firmware somehow
