### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [flipperdevices/Flipper-Android-App#988]
ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8330654328/viewer#L541

so I remove some stuff that's known non-FOSS: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16572/diffs#15ed47849e7fb215392b4d0ba8777d208cc3fb8d_537_544

and clean 2 lines: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16572/diffs#15ed47849e7fb215392b4d0ba8777d208cc3fb8d_537_554

but now it fails: https://gitlab.com/fdroid/fdroiddata/-/jobs/8332194404#L6175

what did I miss?

**Comment by makeevrserg** [comment]
Bug in `components:analytics:metric:noop`. `SingleActivity` require `MetricAndroidApi`, but only `MetricApi` is provided in `components:analytics:metric:noop`

**Comment by LionZXY** [comment]
Sorry, it's our fault

**Comment by licaon-kter** [comment]
thanks, builds fine and (at leasts) starts fine :+1:
